linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
  disable:
    - gosec # We'll handle security separately
    - unused # Too strict for SDK development

linters-settings:
  gofmt:
    simplify: true
  errcheck:
    check-blank: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 10m
  skip-dirs:
    - .archive
    - examples