# Copyright (C) 2023-2024, Lux Partners Limited. All rights reserved.
# See the file LICENSE for licensing terms.

name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
          check-latest: true
      - name: Run static analysis tests
        shell: bash
        run: scripts/tests.lint.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
