name: SDK Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'sdk/**'
      - '.github/workflows/test-sdk.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'sdk/**'
      - '.github/workflows/test-sdk.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        cache: true
        cache-dependency-path: sdk/go.sum
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./sdk/coverage.txt
        flags: sdk
        name: sdk-coverage